<a href="https://colab.research.google.com/github/rsnbgt/python_tutorial/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.0.2


DataTypes and Attributes

In [8]:
# 1-D array
a1=np.array([1,2,3])

#2-D array
a2=np.array([[1,2,3],[4,5,6]])

#3-D array
a3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [9]:
a1.shape , a1.ndim ,a1.dtype ,a1.size , type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [10]:
a2.shape , a2.ndim ,a2.dtype ,a2.size , type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [11]:
a3.shape , a3.ndim ,a3.dtype ,a3.size , type(a3)

((3, 2, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [13]:
# array of ones
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#array of zeros
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# range array
range_array=np.arange(0,10,3)
print(range_array)

[0 3 6 9]


In [17]:
# array of random values
random_array=np.random.randint(0,10,size=(3,3))
print(random_array)

[[5 3 5]
 [9 3 4]
 [5 4 2]]


In [18]:
random_float_array=np.random.rand(3,3)
print(random_float_array)

[[0.23181507 0.69966637 0.03755715]
 [0.51418212 0.36200909 0.59754376]
 [0.18863799 0.78689103 0.61699851]]


Manipulation and comaparison

In [19]:
#Arithmetic
# +, -, *, /, //, **, and %
# np.exp()
# np.log()
# Dot product - np.dot()
# np.square()
# np.sqrt()

In [23]:
# Aggregation
# np.sum()
# np.mean()
# np.std()
# np.var()
# np.min()
# np.max()
# np.argmin() returns indices
# np.argmax() return indices
# np.sort()

In [22]:
# Reshaping
# np.reshape()
# Transposing
# a3.T